trigger:
  - master

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0
  - name: DotNet3Version
    value: 3.1.x
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Windows
    pool:
      vmImage: Windows-2019
    steps:
      - task: UseDotNet@2
        displayName: Setup
        inputs:
          packageType: sdk
          version: $(DotNet3Version)
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: pack
          packagesToPack: Steeltoe.Initializr.WebApi.sln
          arguments: "--configuration $(buildConfiguration) /p:TreatWarningsAsErrors=True"
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: Steeltoe.Initializr.WebApi.sln
