---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: initializr-api
  namespace: initializr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: initializr-api
  template:
    metadata:
      labels:
        app: initializr-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: initializr-api
        image: localhost:5000/initializr-api
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Local
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: initializr-api
  namespace: initializr
spec:
  ports:
  - port: 80
  selector:
    app: initializr-api
